### ISSUE TITLE
Zoom into any picture  - Check Order status page

### ISSUE THREAD

**Issue by AndroidAkyl** [hasan5151/autoparts#3]
![image](https://cloud.githubusercontent.com/assets/26451941/24089228/a0b46ffa-0d5e-11e7-8690-b9a61b255512.png)
![image](https://cloud.githubusercontent.com/assets/26451941/24089244/d7d19dfa-0d5e-11e7-851f-73e5c8fd3e23.png)
I think users need to able to zoom in pictures 
To play the enhancement go to : 
1. Autoparts 
2. Check Order status 
3. Click into any order

**Comment by hasan5151** [comment]
![](http://127.0.0.1:61347/device/3100c6309885c257/screenshot.jpg)

**Comment by hasan5151** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17989735/24095147/e67ee9d0-0d85-11e7-9fd3-55ced23921b2.jpg)
